DROP TABLE IF EXISTS `audit`;
CREATE TABLE `audit` (
  `ID` char(32) NOT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `session_id` varchar(32) DEFAULT NULL,
  `xpid` char(32) NOT NULL,
  `when` datetime DEFAULT NULL,
  `source_ip` varchar(50) DEFAULT NULL,
  `URL` longtext NOT NULL,
  `module` varchar(255) NOT NULL,
  `action` varchar(255) DEFAULT NULL,
  `proc_required` varchar(255) DEFAULT NULL,
  `transac_data` longtext,
  `type` enum('GET','HEAD','POST','PUT') NOT NULL,
  `messages` text NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `user_id` (`user_id`),
  KEY `session_id` (`session_id`),
  KEY `source_ip` (`source_ip`),
  KEY `action` (`action`),
  KEY `process` (`proc_required`),
  KEY `when` (`when`),
  KEY `type` (`type`),
  KEY `module` (`module`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
