#!/bin/sh

### BEGIN INIT INFO
# Provides:		php-java-bridge
# Required-Start:	$mysql-server $apache2
# Required-Stop:	$mysql-server $apache2
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Provides java service to php scripts
# Description:		Provides java brigde to php scripts
### END INIT INFO

XPOTRONIX_LIB=/usr/share/xpotronix/lib

case "$1" in
  start)
    echo "Starting JavaBridge ..."
    cd /var/www/sites/
    sudo -u www-data java -Xms32m -Xmx64m -jar $XPOTRONIX_LIB/webapp-runner.jar --access-log  $XPOTRONIX_LIB/JavaBridgeTemplate.war&
    echo $! > /var/run/JavaBridge.pid
    ;;
  stop)
    echo "Stopping JavaBridge"
    PID=`cat /var/run/JavaBridge.pid`
    kill -9 $PID
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0
