#!/bin/sh

### BEGIN INIT INFO
# Provides:		php-java-bridge
# Required-Start:	$mysql-server $apache2
# Required-Stop:	$mysql-server $apache2
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Provides java service to php scripts
# Description:		Provides java brigde to php scripts
### END INIT INFO

XPOTRONIX_JAR_PATH=/usr/share/xpotronix/lib

# java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home'

JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
WORKDIR=/var/www/sites/

JAVA_OPTIONS=" -Xms256m -Xmx512m -server "
APP_OPTIONS=" -c /path/to/app.config -d /path/to/datadir "

case "$1" in
  start)
    echo "Starting JavaBridge ..."
    cd $WORKDIR
    sudo -u www-data "${JAVA_HOME}/bin/java" $JAVA_OPTIONS -jar $XPOTRONIX_JAR_PATH/webapp-runner.jar --access-log  $XPOTRONIX_JAR_PATH/JavaBridgeTemplate.war
    echo $! > /var/run/JavaBridge.pid
    ;;
  stop)
    echo "Stopping JavaBridge"
    PID=`cat /var/run/JavaBridge.pid`
    kill -9 $PID
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0
