#!/usr/bin/php
<?


// ini_set( 'xdebug.profiler_enable_trigger', 0 );
// ini_set( 'xdebug.collect_params', 2 );
// ini_set( 'xdebug.show_mem_delta', 1); 
// xdebug_start_trace('/tmp/xpotronix-trace.xt');


ini_set( 'display_errors', 1 );
ini_set( 'log_errors', 1 );
ini_set( 'error_log', 'syslog' );


$ini = parse_ini_file( '/etc/xpotronix/xpotronix.ini', true);
require_once $ini['paths']['lib']. "xpmessages.class.php";
require_once $ini['paths']['lib']. "includes/misc_functions.php";

$params = parseParameters();

if ( ! isset( $params['path'] ) ) {

	M()->fatal( "debe especificar el base path de la aplicacion con el parametro --path" );
	exit( 1 );
}

chdir( $params['path'] );
ini_set( 'include_path', ini_get( 'include_path' ). ".:/usr/share/php/adodb:{$ini['paths']['lib']}" );


include_once $ini['paths']['lib']. "main.php";


// xdebug_stop_trace();

?>
