#!/usr/bin/php
<?php


// ini_set( 'xdebug.profiler_enable_trigger', 0 );
// ini_set( 'xdebug.collect_params', 2 );
// ini_set( 'xdebug.show_mem_delta', 1); 
// xdebug_start_trace('/tmp/xpotronix-trace.xt');

//ini_set( 'display_errors', 0 );
//ini_set( 'log_errors', 1 );
//ini_set( 'error_log', 'syslog' );

//ini_set( 'include_path', ini_get( 'include_path' ). ':/usr/share/php/adodb' );

require __DIR__. '/../vendor/autoload.php';

$params = parseParameters();

isset( $params['path'] ) or $params['path'] = '.';

if ( ! @chdir( $params['path'] ) ) {

	M()->fatal( "No puedo acceder al directorio {$params['path']}. Proceso cancelado" );
	exit(1);
}

require $params['path']. "/index.php";

// xdebug_stop_trace();

?>
